name: 'Build Container Action'

description: 'Builds and caches the image'

inputs:
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true

runs:
  using: "composite"
  steps:
  - name: Make date tag
    id: mkdatetage
    run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"
    shell: bash

  - uses: actions/checkout@v2

  - name: Generate tag list
    id: generate-tag-list
    env:
      REPO: ${{ input.repo }}
      TIMESTAMP: ${dtag}
    run: |
      docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
      tag_list=$docker_repo:$REPO,$docker_repo:$REPO-$TIMESTAMP
      echo "::set-output name=taglist::$tag_list"
    shell: bash

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Log in to Docker Hub
    uses: docker/login-action@v1
    with:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}

  - name: Build and push Docker images
    uses: docker/build-push-action@v2.2.0
    with:
      push: true
      build-args: BASE_YUM_REPO=${{ input.repo }}
      tags: "${{ steps.generate-tag-list.outputs.taglist }}"
