name: 'Build Container Action'

description: 'Builds and caches the image'

inputs:
  repo:
    description: 'Input string that gets passed along to the docker build args'
    required: true
  tag_list:
    description: 'List of tags that gets passed along to the docker build args'
    required: true
    default: '' # set to an empty string

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: Generate tag list
    id: generate-tag-list
    env:
      REPO: ${{ inputs.repo }}
      TIMESTAMP: $(date +%Y%m%d-%H%M)
    run: |
      docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
      tag_list=$docker_repo:$REPO,$docker_repo:$(date +%Y%m%d-%H%M)
      echo "::set-output name=taglist::$tag_list"
    shell: bash

  - name: Set up Docker Buildx
    uses: docker/setup-buildx-action@v1

  - name: Build and push Docker images
    uses: docker/build-push-action@v2.2.0
    with:
      push: false
      build-args: BASE_YUM_REPO=${{ inputs.repo }}
      tags: "${{ steps.generate-tag-list.outputs.taglist }}"
